version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-planit
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_DATABASE: planit_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
